stages:
  - sast
  - test
  - package
  - tailwind

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

cache:
  paths:
    - .m2/repository
    - node_modules/
    - .pnpm-store/
  key:
    files:
      - pnpm-lock.yaml

sast:
  stage: sast
  allow_failure: true
  needs: [ ]
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# -> (-) MongoDB
package:
  stage: package
  image: maven:3-openjdk-17
  script: "mvn package -Dmaven.test.skip"
  artifacts:
    when: always
    paths:
      - target/*.war
      - target/doodle*

tailwind:
  stage: tailwind
  image: node:alpine
  before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  script:
  - pnpm i
  - pnpm build:tailwind
  artifacts:
    when: always
    paths:
      - /src/main/webapp/css/*.css


